"""empty message

Revision ID: 7e0f691eb5c5
Revises: aa57ac61df92
Create Date: 2023-05-22 01:21:26.826932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0f691eb5c5'
down_revision = 'aa57ac61df92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('ticket_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint('uq_event_ticket_type', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_event_ticket_type', ['event_id', 'ticket_type'])
        batch_op.alter_column('ticket_price',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
