"""empty message

Revision ID: 83ae572ce368
Revises: d9ae8afc5dfe
Create Date: 2023-05-22 17:04:45.308682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ae572ce368'
down_revision = 'd9ae8afc5dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('event_start_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('event_end_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('event_end_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('event_start_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
