"""empty message

Revision ID: a2b954cc9b3e
Revises: aa21231364dd
Create Date: 2023-05-23 22:02:59.548263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b954cc9b3e'
down_revision = 'aa21231364dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('confirmEmail', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cardNumber', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expirationDate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('securityCode', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('zipCode', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('zipCode')
        batch_op.drop_column('securityCode')
        batch_op.drop_column('expirationDate')
        batch_op.drop_column('cardNumber')
        batch_op.drop_column('confirmEmail')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
