"""empty message

Revision ID: a5b8e35730e5
Revises: 8ceba11ea21c
Create Date: 2023-05-22 10:13:46.473796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b8e35730e5'
down_revision = '8ceba11ea21c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_preview_image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('event_description_image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('event_description_image')
        batch_op.drop_column('event_preview_image')

    # ### end Alembic commands ###
