"""empty message

Revision ID: d9ae8afc5dfe
Revises: a5b8e35730e5
Create Date: 2023-05-22 17:03:38.977159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ae8afc5dfe'
down_revision = 'a5b8e35730e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('event_start_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('event_end_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('event_end_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('event_start_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
